# Generated by Django 5.1.4 on 2025-02-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together={('filename', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['filename', 'created_at'], name='api_newslet_filenam_b3640a_idx'),
        ),
    ]
