# Generated by Django 5.1.4 on 2025-02-23 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('email', 'topic')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['email', 'topic'], name='api_subscri_email_b4e2aa_idx'),
        ),
    ]
