# Generated by Django 5.1.4 on 2025-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_newsletter_created_at_alter_subscription_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
